"""add user is active flag

Revision ID: 7dce744b891c
Revises: 2aa3a3ca9b8b
Create Date: 2023-09-04 14:29:56.998376

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "7dce744b891c"
down_revision: Union[str, None] = "2aa3a3ca9b8b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
