version: "3"

services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sqlatraining
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data:delegated

volumes:
  pg-data: null
